### ISSUE TITLE
Wallet Class Structure

### ISSUE THREAD

**Issue by skubakdj** [MyEtherWallet/MyEtherWallet#103]
Hey everyone!

Let's use this issue to determine our class structure for the different wallet types we support. I've piggybacked on what's currently in our codebase and divised a simple structure that I hope will be a good starting point for discussion: 

```
BaseWallet
|   getAddress()
|   getNakedAddress()   
|
|__ PrivkeyWallet( privkey )
|   |   privKey
|   |   pubKey
|   |   address
|   |   generate()
|   |   getPrivateKey()
|   |   getAddress()
|   |   toKeystoreFile()
|   |   signRawTransaction()
|   |   signMessage()
|   |        
|   |__ EncryptedPrivkeyWallet( key, pass )
|   |       super( decryptPrivateKey( key, pass ) )
|   |
|   |__ MnemonicWallet( phrase, pass )
|   |       super( decryptMnemonicPhraseToPrivkey( phrase, pass ) )
|   |
|   |__ KeystoreWallet( keystore, pass )
|   |       super( decryptKeystoreToPrivkey( keystore, pass ) )
|   |
|   |__ PresaleWallet( presale, pass )
|           super( decryptPresaleToPrivkey( presale, pass ) ) 
|
|__ LedgerWallet
|       address
|       signRawTransaction()
|       signMessage()
|
|__ TrezorWallet
        address
        signRawTransaction()
        signMessage()
```

To summarize, all wallets inherit from `BaseWallet` and any wallet dependent on deriving a private key (`EncryptedPrivkeyWallet`, `KeystoreWallet`, `PresaleWallet`, `MnemonicWallet`) is essentially a wrapper for `PrivkeyWallet`. All wallets should come equipped with methods to sign transactions and messages (`signRawTransaction()` & `signMessage()`, respectively). 

Additional work will probably have to go into `LedgerWallet` and `TrezorWallet`, specifically dealing with HD key paths & verifying addresses exist. 

Please let me know what y'all think :smile: 

@dternyak  @crptm @wbobeirne

**Comment by wbobeirne** [comment]
Great diagram!

Seems to me that all wallets will have a `signRawTransaction()` as well, but that's not shared in any way that I see here. But this is a great idea to standardize, to get rid of [shit like this](https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/uiFuncs.js#L114).

One thing I see a lot of in v3 is separate conditionals for each hardware wallet to do their unlocking behavior. I think it would be great to either:
1) Have a `HardwareWallet` class that standardizes this behavior
2) Have all wallet classes have this behavior, but wallets that don't need to, simply resolve the promise immediately

I think 1 should happen for sure, but I kind of like the idea of 2 for code simplicity. That way we can just always call `wallet.unlock().then( /* rest of stuff */ )` and avoid conditional soup.

You could also take that idea further and have `unlock`ing be implemented by everything, just have some of them be synchronous and resolve with promises after doing they checks they would normally do in their constructor.

**Comment by dternyak** [comment]
Awesome diagram @skubakdj!

@crptm And I had a discussion about having an async API for all wallet classes, and came to the same conclusion of having an the immediate resolve pattern @wbobeirne mentioned above.

So far, I can identify the following methods that would be async:
1. `unlock` (as @wbobeirne mentioned above)
2. `signMessage`
3. `getAddress`
4. `signRawTransaction`
5. `signMessage`

All wallet classes should implement this basic interface, and since hardware / managed wallets will be async, we can avoid the "conditional soup" when interacting with a wallet instance as @wbobeirne mentions, and should result in simpler code overall. 

Since parity phrases are no longer supported, we would only need to resolve immediately since we would already have the private key for:
1. UTC wallets
2. Raw private keys

**Comment by wbobeirne** [comment]
That all sounds dope 👍 

The only thing I'm still not clear on is how we'll handle the additional UI of unlocking as a part of the promise. Not to mention selecting the path and address. It'd be a little odd to have a `*Wallet` class dispatch to redux store or something like that.

Perhaps we could have a function that takes in a wallet as an arg, and handles the reducer side of it? Something like:

```
// Fires `WALLET_UNLOCK`, followed by `WALLET_UNLOCK_SUCCESS` or
// `WALLET_UNLOCK_FAILURE` upon unlocking. Also potentially calls
// `WALLET_UNLOCK_SELECT_PATH_AND_ADDRESS` or something
// along the way.
uiUnlock(wallet).then((unlockedWallet) => {
  /* Whatever */
});
```

**Comment by dternyak** [comment]
I like it! Great idea, didn't think about state management yet.

**Comment by skubakdj** [comment]
Really love the idea of keeping a standard async api throughout, that will **greatly** simplify wallet interaction :+1: 

@dternyak could we confirm the different private key wallets we'll be supporting? I think there might be a few more for which we can resolve resolve immediately. From issue #80 :

1. `UTC wallets`
2. `Raw private key`
3. `Encrypted private key`
4. `Presale JSON` 
5. `BIP39 Mnemonic`

Side note -- browsing the live v3 site, I'm guessing the `Mnemonic Phrase` option is the BIP39 implementation and, interestingly, I don't see a selection for `Presale JSON`, though I think it may have been around in previous versions.

**Comment by dternyak** [comment]
@skubakdj I think @tayvano should actually confirm here :)

**Comment by tayvano** [comment]
1. UTC / Keystore / v3 files. These are the standard wallet files created by geth. That would be the `tov3()` method here: https://github.com/ethereumjs/ethereumjs-wallet#remarks-about-tov3
    - The n value cannot be `262144` in browser. It has to be a um...thing. Like 1024...2048....etc. We should run test to see how high we can get it while not breaking browsers.

2. Yup. ✅

3. This is same input as #2 but if its not 64 characters, then you show a password dialog. This is not something we generate anymore. `fromEtherWallet(input, password) - import a wallet generated by EtherWallet` here: https://github.com/ethereumjs/ethereumjs-wallet#thirdparty-api 

4. Yup. JSON file. `fromEthSale(input, password)` https://github.com/ethereumjs/ethereumjs-wallet#wallet-api

5. Yup. User should be able to select any path. I would recommend using the existing libraries in V3 as we spent a lot of time figuring that shit out. This has an optional password. Can be any number of words. 

- Trezor, Ledger, Digital Bitbox, via web3 will be methods in future where you only have address, not PK. We should set something so that we can adjust things easily based on whether we have access to key or not, not based on specific format of key.

- Also just found this which may be salvageable? https://github.com/MyEtherWallet/mew-wallet (prob not)

- HD paths are a shitstorm. Do not try to understand. Do not change. :P https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/controllers/decryptWalletCtrl.js#L11-L26

- We should assume that we do not have the actual private key (for cases like Ledger / TREZOR)

- We will likely add a "connect via web3" item IF you detect web3 in browser. Metamask team can provide guidance. Find kumavis in the dreamteam channel. 

- Longest running request ever: encrypt a private key on MEW. (just keep in mind. no need to do it now if it's a pain. Not high priority.)

**Comment by crptm** [comment]
PKeyWallet should have toKeystore(password). Sign should not be on all classes because of 'view with address only' - we might reconsider it if we have address first flow everywhere. unlock().then() wouldnt work bc it needs custom UI

**Comment by crptm** [comment]
If we have address first flow, we could have same async unlock flow for hw/regular wallets. MEW key apps need a bit different logic. We should have something like GetUnlockComponent(): Component<Props>, where Props:

```
{
  tx: Transaction,
  onTxSign(signedTx?) // for regular wallets
  onFinish() // for mew key like flow when component handles broadcasts, 
             // so we have a point to reset relevant page state/reload balances
  onError()
}
```

**Comment by skubakdj** [comment]
So for example, if we had a private key wallet with address-first flow, would we only ask for a user's address in the `Wallet Decrypt` component, and then later ask for the private key only when they try to sign something?

**Comment by tayvano** [comment]
Correct. This may be easier to do in general, considering it is the flow for hardware wallets & MetaMask and any iPhone signers (like the one Glenn is working on). Basically it would use same flow for everyone. There is a non-working branch on v3 that does this. You select private key / keystore file and instead of the file you enter your address. When you go to sign it, itll pop up a modal asking for your actual file so that it can sign it.

**Comment by dternyak** [comment]
Closing - happy to re-open if we need to continue this design discussion.
