### ISSUE TITLE
When I click on the link in the ropsten network will jump to the rinkeby.etherscan.io

### ISSUE THREAD

**Issue by ProDog** [MyEtherWallet/MyEtherWallet#1119]
![image](https://user-images.githubusercontent.com/12728872/58393838-0a112180-8073-11e9-9dbc-9ccb1e2616a9.png)

As shown in the figure, if I click this link in the ropsten network, it will jump to the rinkeby.etherscan.io

thanks！

**Comment by kvhnuke** [comment]
I believe you sent that tx in rinkeby as the values are also in `RIN`, rinkeby is also a testnet for Ethereum

**Comment by ProDog** [comment]
It's in  ropsten,I'm sure.
https://ropsten.etherscan.io/tx/0x9fb841bd2805949494f39f172784452c90c3def4fa49d5ec83e52f67eb0a48e0

**Comment by SteveMieskoski** [comment]
@ProDog are you using a custom network?

**Comment by ProDog** [comment]
> @ProDog are you using a custom network?

no

**Comment by SteveMieskoski** [comment]
Strange. because the the explorer path is generated based on the current network (to keep down on the volume of information), and the notifications listed are filtered by network such that only those for the current network are shown. So it shouldn't be showing rinkeby notifications when (based on the link) the current network should be Ropsten.   I'll try to recreate to see why this is happening.
