### ISSUE TITLE
[Future-Proof] By default, new networks should have hardware wallets disabled

### ISSUE THREAD

**Issue by tayvano** [MyEtherWallet/MyEtherWallet#128]
By default, new networks should have hardware wallets disabled until the creator of the network or the hardware wallet confirms the correct path / that it's good to go.

Apparently there are some unforeseen issues with non-Ethereum networks (musicoin) and hardware wallets that don't make sense to be, but let's be sure to fail safe.

edit after more info:

1. No non-EIP-155 chains should ever be added

2. Sign off required from network creator + hardware wallet (Ledger / TREZOR / Digital Bitbox) before merging. 

3. By default, any new networks do not have hardware support

4. Figure out what the fuck path for the network. If not clear / officially in BIP44, do not merge.

**Comment by trustfarm-dev** [comment]
@tayvano  I think Hw wallet is needs for supports.
Because they just provide private key encryptions.
So, If there's default / general path for storing the Private Key, then Trezor should inform it.
I think , It is not a good approach , What Trezor not support general key storage for several coin, MEW doesn't accept Coin wallet.

it just change using default path of Trezor.

Finally, like this restriction , It makes another version of forking of MEW.
@immartin
And, Now Musicoin doesn't support of EIP-155 now. but, It is same as early of ETH.
Even though it doesn't support EIP-155, replay problem is very rare and all other token on MEW .
they support EIP-155 now. So, attaching before replay attack preventing contract and New version of Musicnode support EIP-155, I think there's no problem on ETH / ETC in MEW tokens.
