### ISSUE TITLE
Hardware / Mnemonic wallet modal proposal

### ISSUE THREAD

**Issue by wbobeirne** [MyEtherWallet/MyEtherWallet#129]
As someone relatively new to crypto, I was a little confused about the current hardware wallet modal. Specifically the concept of derivation paths. The current modal, for reference:

<img width="819" alt="screen shot 2017-08-21 at 2 56 54 pm" src="https://user-images.githubusercontent.com/649992/29533716-2c287932-8681-11e7-823a-f256fb992991.png">

I had the following questions when I first saw this:

* What is a derivation path?
* Do I need to change this?
* The one I selected mentions Jaxx, Metamask etc. Is that OK?
* What happens when I click "More addresses"? How many are on here? Can I go back?

After working on Trezor for a bit, I've realized that a lot of this stems from the re-use of the same modal for mneumonic wallets. I think it would be smart to keep that re-use, but tailor the modal for each hardware wallet via component props and make this a little simpler.

I put together some wireframes (These are NOT designs, just wireframes) of what I think would keep it simpler, without sacrificing the abilities offered from the current one. I'm not sure I captured _every_ state needed, but this should be enough to go off of when we implement this.

[select-address.pdf](https://github.com/MyEtherWallet/MyEtherWallet/files/1240030/select-address.pdf)

I'm still a little hazy on the derivation paths and BIP44, so please let me know if I lost anything in this simplification. CC @dternyak @crptm @skubakdj @tayvano for feedback.

**Comment by crptm** [comment]
👍  not sure if all hw wallets support passing derivation path.

**Comment by tayvano** [comment]
Yeah its a total shitshow. The problem is if you don't give them the ability to do derivation paths, you will have endless amounts of users unable to access their ETH they sent to an ETC path and vice versa.  There is no doubt a better way to handle it and we should handle it better. 

Right now the most common email regarding HD paths, surprisingly enough, is **not** confusion regarding which path—most just leave it unchanged—which is why the modal itself has remained the hot mess it is *(if it ain't broke....)*

The most common email is: "I sent my ETC to my Jaxx ETH wallet and now it's lost and they told me to contact you" to which we tell them how to find their ETC and they are very happy campers and now use MEW. 🤷 

I would propose:

- Making sure every path is best path depending on mnemonic phrase / hardware wallet / network. 

- Giving users the ability to select a different one via a dropdown

- Placing a warning if they try to change it that they should be careful and email us if they need assistance or clarification. 

Furthermore, we *can* choose to ping the node and get the balances of their accounts on each path or different paths if we wanted to. We would need to limit the number of requests but it would be doable. This would be a better user experience, but we need to tradeoff between (1) pinging multiple addresses for ETH balances (2) pinging 3 addresses for ETH + Tokens.

Which brings me to my next point: we should check the token balances in this modal dialogue. It irks me endlessly. However, 100 tokens x 5 address = 500 requests each time this modal opens. 

Perhaps we put this latter point on back-burner until we determine best way to efficiently check token balances first (in a new issue)

**Comment by tayvano** [comment]
Another thing to think on is the naming scheme for `TREZOR (ETH)` vs `TREZOR (ETC)`. 

You have the NETWORK you are currently on (eth vs etc) and you have the path TREZOR uses for each of those network. This results in 4 available "paths" for TREZOR that people tend to send to:

- ETH is sent to ETH Path (correct)

- ETH is sent to ETC Path

- ETC is sent to ETC Path (correct)

- ETC is sent to ETH Path

However, conceptually, this is a total mindfuck and I don't think `TREZOR (ETC)` does a good job at explaining exactly what is happening.

**Comment by wbobeirne** [comment]
> The problem is if you don't give them the ability to do derivation paths, you will have endless amounts of users unable to access their ETH

Understood, the last option in the select list would replace it with a text field for manual entry so we wouldn't be taking that away.

> Making sure every path is best path depending on mnemonic phrase / hardware wallet / network.

Yep, I'm thinking the dropdown would only be pre-populated with reasonable options for your wallet. Each wallet decrypt component will specify which addresses to show, with the first one being the default.

> Giving users the ability to select a different one via a dropdown

Definitely, in the wires.

> Placing a warning if they try to change it that they should be careful and email us if they need assistance or clarification. (a brief overview could be where you have the ( ? ) icon and it could end with cta to email us if still confused)

I like this idea, maybe only for some of the unorthodox options, but definitely for the custom path.

---

To your last point, I'd need to know more about why that happens so often, but I'd think if someone was told "You sent that to your ETC address, not your ETH address." That it wouldn't be too hard to expect them to change the thing that says ETH to ETC when they pick their address. But maybe I have too high hopes.

As for tokens, perhaps we add another column where users can select _one_ token to preview. That way we're only doing n*2 requests, and users can select from a dropdown of tokens to preview. Presumably they're usually looking for that one OMG / REP / XMR wallet, not trying to get an overview of their full portfolio.

**Comment by tayvano** [comment]
> To your last point, I'd need to know more about why that happens so often, but I'd think if someone was told "You sent that to your ETC address, not your ETH address." That it wouldn't be too hard to expect them to change the thing that says ETH to ETC when they pick their address. But maybe I have too high hopes.

Nope, that's exactly what we do now (well, except we tell them usually that they need to change the node). Problem stems from other UIs actually. You cannot access your ETC or ETH on a different path. So people, not thinking or whatever, send their ETC to their ETH address and then they can't access that address on ETH and they can't access ETC on their ETH address and then we add another user to our collection. 

I think I've mentioned it before but one of the reasons our userbase numbers are so high is that all the other wallets send people to us for one reason or another. This is one of those. We specifically have an auto responded for Jaxx ETC people. 🙃 

Anyways, I think we are totally on the same page and I'm.veey happy with your wireframes and understanding of the problem and your proposed solution(s). We can iterate if this creates misunderstanding or confusion. 

I haven't talked to you about this but we hope to add some basic usage analytics to v4 to get a better understanding of these sorts of things. Itll be interesting to see if 99% of our users don't select a different path or if a lot do.

**Comment by jhoenicke** [comment]
Some more things to consider:

I think the derivation paths should not be visible by default.  There should be a button "Find my lost coins" that unhides the part where you select a different path.

This part should have two options:  1. wallet (Ledger/Trezor/Jaxx/Metamask/.../custom),  2. coin (ETH/ETC/Testnet/RSK/EXP/UBQ).  Everything initialized to sensible defaults.  Custom would not show the coin option, but give you the possibility to enter the BIP-32 path for people who know what they are doing (or were told so by support).  Is it currently the case that all wallets except Ledger always want to use m/44'/coin'/0'/0/x as derivation path?  Then the first field would only have the choices Ledger, All other, and custom.

The addresses should probably be numbered (starting with 0); this gives a little more reassurance that you can find your address if you remember its number.

One problem is that mnemonic can be used to recover from any wallet, so Ledger users would have to  press the "Find my lost coin" button to find their Ethers.  But this could be documented in the Ledger manual (what to do if I lose my hardware wallet).

**Comment by prusnak** [comment]
> you will have endless amounts of users unable to access their ETH they sent to an ETC path and vice versa

The problem is, with the current dialog, MEW is producing more and more people like this.

I agree it is nice to have this function, but it should be hidden from users in some advanced dialog. Or even completely hidden from the UI and accessible only via URL that you'll send to such people in need. Once they send their funds to correct addresses, they won't be needing that interface anymore.

**Comment by dternyak** [comment]
Thank you @jhoenicke and @prusnak for your comments. 

We will do another round of UX review closer to V4 stable release, and will try our best to take your suggestions into account 👍

**Comment by wbobeirne** [comment]
This has since been implemented
