### ISSUE TITLE
Investigate HMR

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#198]
According to various reports, hot-module replacements appear to not always be taking effect.

**Comment by wbobeirne** [comment]
This is probably because of the blanket `module.hot.accept();` in `index.jsx`. We may want to limit that to `containers/*` and `components/*`. The [official webpack guide to HMR](https://webpack.js.org/guides/hot-module-replacement/) doesn't offer too much in terms of assistance for how HMR might work for other things (Sagas, lib functions, etc.)

**Comment by HenryNguyen5** [comment]
https://stackoverflow.com/questions/37148592/redux-saga-hot-reloading

This is related, I've gotten the same error described in that article

**Comment by wbobeirne** [comment]
I see this got rolled back, can we just re-implement by accepting `containers/*` and `components/*`, and figure out sagas / libs / utils later? Don't wanna throw out the baby with the bathwater, those hot reloads were 👌

**Comment by dternyak** [comment]
@wbobeirne Poor baby's been thrown out for a while. I'll try to put him back in his crib 😁

**Comment by dternyak** [comment]
HMR is partially working, issue can be re-opened should we feel the need to further improve it.
