### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by jclancy93** [MyEtherWallet/MyEtherWallet#2]
Sorry know this probably isn't the best place to leave this, didn't know where else to reach out. Just wondering what happened to all the PRs/issues/stars?

**Comment by johnzweng** [comment]
@jclancy93 If you are wondering: this here seems not to be the official myetherwallet repo (or if so, it is a new account).

Since the early days of myetherwallet there was always this repo here linked on the website footer: https://github.com/kvhnuke/etherwallet/

There you also have all the issues, PRs, stars you were missing.

**Comment by jclancy93** [comment]
@johnzweng Thats actually the repo for v3. The repo for v4 has now moved to a different location, it used to be here, thats where my confusion stemmed from. Thanks for the advice though 👍
