### ISSUE TITLE
Print paper wallet regression

### ISSUE THREAD

**Issue by wbobeirne** [MyEtherWallet/MyEtherWallet#225]
Not sure when this happened, but the paper wallet that pops up to print is missing a lot of info:
<img width="1095" alt="screen shot 2017-09-23 at 1 18 58 pm" src="https://user-images.githubusercontent.com/649992/30775458-e358856c-a061-11e7-8caa-c64540daf262.png">

**Comment by wbobeirne** [comment]
I'm willing to be this happened when we went async with address, given those are the pieces missing. Were we ever going to re-re-factor it to be sync again?

**Comment by dternyak** [comment]
I'm not able to re-produce this after 10+ tries. If its a race condition this could be expected, but I'm unable to determine this issue as of yet.

**Comment by tayvano** [comment]
Another option would be to have the page itself print rather than the pop-up. We could hide the excess information via print styles (css). As long as its not a ton of black ink / pages, I dont see a downside if it eliminates this issue.

Weird sidenote, but if we could put the version of MEW somewhere on the paper wallet, that would probably be a good idea. Not sure why Ive never done it before. 

Lastly, the background image of the address-icon only works in Chrome. There may be a way to get it to work in Firefox / others. Not sure.

**Comment by dternyak** [comment]
@wbobeirne Can this be closed? I haven't been able to re-produce after numerous attempts. Is this an unlikely intermittent issue or do you think it may have already been fixed by unrelated commits?

**Comment by wbobeirne** [comment]
I'll investigate again and close if I can't reproduce.

**Comment by dternyak** [comment]
I am able to re-produce now. Fix is open at https://github.com/MyEtherWallet/MyEtherWallet/pull/292/files
