### ISSUE TITLE
New popup for issue log (Error Logger)

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#226]
- **I'm submitting a ...**

  - [x] Feature request

![image](https://user-images.githubusercontent.com/31494364/49621591-fd8cf580-f97a-11e8-8cac-a3d6b83ae269.png)

- **Feature Request**

  - Briefly explain the feature you would like us to implement
Add a popup that something goes wrong while user using MyEtherWallet, and make sure user could send/email the log issue to MEW force team as well.

**Comment by kvhnuke** [comment]
@gamalielhere and @SteveMieskoski 
- Vue provides a standard API to add a custom errorHandler. You should configure this on your root Vue instance

```
Vue.config.errorHandler = err => {
  console.log('Exception: ', err)
}
```

- To handle errors globally across your entire page, you can add a handler to the onerror function on the window.
```

window.onerror = function(message, source, lineno, colno, error) {
  console.log('Exception: ', error)
}
```

Instead of using `console.log` and `console.error` we should have a custom error handler whenever there is an error above popup will show up and user can either report the error to us or cancel. This way we can track all the errors and fix them easily since we have a complete error log

For reporting, we should explore direct http post to google forms. We can create a form and post directly to it. This will help is prevent spam attacks

Reference
https://dzone.com/articles/error-tracking-with-vuejs

**Comment by hsurf22** [comment]
New(IssueLogModal) modal component added to header container.
- Modal location: /src/components/IssueLogModal

**Comment by hsurf22** [comment]
https://github.com/MyEtherWallet/MyEtherWallet/commit/f928f4394c4a35ac67ac5dc67c2b93988e908518

f928f4394c4a35ac67ac5dc67c2b93988e908518
