### ISSUE TITLE
Token list won't load via MetaMask

### ISSUE THREAD

**Issue by stephenmew** [MyEtherWallet/MyEtherWallet#246]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?

When connecting via MetaMask, the token list will not load.

  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Connect via MetaMask on MyEtherWallet ETH node
Token list does not load

  - What is the expected behavior?

Token list loads

  - What is the motivation / use case for changing the behavior?

To see tokens

  - Please tell us about your environment:
    - Operating system
Windows 10

    - Browser and version
Chrome 70.0.3538.110

**Comment by kvhnuke** [comment]
good observation this is definitely due to the fact that, metamask is using `infura` and they currently have a bug https://github.com/INFURA/infura/issues/165

However, we should have a fallback.
@gamalielhere can we implement a fallback where if loading tokens via our public token contract fail, itll fall back to our old school loading where users have to click `load` to load the specific balance. Specially on ETH network since there are more than 1000+ tokens

**Comment by kvhnuke** [comment]
also, users should be able to change the network via
