### ISSUE TITLE
MEW problems with Uniswap

### ISSUE THREAD

**Issue by jkprag78** [MyEtherWallet/MyEtherWallet#2642]
- **I'm submitting a ...**

  - [* ] Feature request
  - [ ] Bug report

- **Feature Request**

  Unable to process swap. Didin't work with Brave, tried Chrome as well. Got to the confirmation, sign the transaction with my pass but: Swap failed: Cannot read property 'nonce' of undefined (that was using Brave)

**Comment by abbaskiko** [comment]
> * **I'm submitting a ...**
>   
>   * [* ] Feature request
>   * [ ]  Bug report
> * **Feature Request**
>   Unable to process swap. Didin't work with Brave, tried Chrome as well. Got to the confirmation, sign the transaction with my pass but: Swap failed: Cannot read property 'nonce' of undefined (that was using Brave)

**Comment by SteveMieskoski** [comment]
@abbaskiko and @jkprag78 what method(s) were you using to access your wallet?

**Comment by melyalex** [comment]
> @abbaskiko and @jkprag78 what method(s) were you using to access your wallet?

Myetheriumwallet mew wAlley

**Comment by abbaskiko** [comment]
I think my report or contact to you for my problem for about 1 month ago
maybe I can't remember exactly but if I doesn't mistake my problem is I
have too many address and when I use my recovery 12_24 words its show many
address etherum wallet I know I have some uniswap coin from contract but
can't find my address because I lost my wallet and now recovery code
doesn't help
Its for that I chose option that when I use contract and like that my
address will change

KIKO

در تاریخ ۱۲ دسامبر ۲۰۲۰ ۱۴:۳۳، "Melissa Lunardi" <notifications@github.com>
نوشت:

**Comment by melyalex** [comment]
Unable to process swap. Didin't work with Brave, tried Chrome as well. Got to the confirmation, sign the transaction with my pass but: Swap failed: Cannot read property 'nonce' of undefined (that was using Brave)
