### ISSUE TITLE
Creating offline tx not working for MetaMask account

### ISSUE THREAD

**Issue by ligi** [MyEtherWallet/MyEtherWallet#312]
It is working for me when I use a private-key. But when using for some MetaMask Account it is not generating the signed tx. Both sides are JSON - the right side should be RLP encoded signed tx as hex like it is when using a private key.
Looks like this:
![selection_168](https://user-images.githubusercontent.com/111600/31903708-369f922c-b829-11e7-8838-45e4ec118afb.png)

**Comment by skubakdj** [comment]
Hi @ligi! This is the repository for MyEtherWallet v4, a complete rewrite of the project that's currently in alpha. You probably meant to open an issue on the production repo, [which can be found here](https://github.com/kvhnuke/etherwallet). 

`web3` providers don't allow for transactions to be signed and returned to the client. Instead, signing and broadcasting to the network occurs in one step, the result of which is a transaction hash. Since we can't grab this data, the `Signed Transaction` field has simply been stubbed out with the JSON that MetaMask will sign.
