### ISSUE TITLE
Clear Wallet Instance

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#707]
Currently, the wallet instance is only unset when leaving the `Account View & Send` tab.

- [ ] Clear wallet state when a user exists the following routes: 
1. Sign and Verify (depending on in if they signed in to sign a message, or only verified)
2. Contracts (depending on if they signed in to broadcast a contract)
3. Swap (depending on if they hit stage 3 and activated lite send. 

Future:
- [ ] Clear state when exiting ENS.

**Comment by wbobeirne** [comment]
Probably the easiest way to do this would just be to have one componentWillUnmount on TabSection component, or to have something watch path changes and remove the instance if the base path changes (i.e. /account/send to /account/info won't remove it, but /account/send to /sign-and-verify would.)

Likewise, we could also move the logout notification to tab section, just "render" it (so that it'll show on navigation) when they have a wallet in redux.
