### ISSUE TITLE
Actions in MetaMask Account/Send throw MetaMask errors

### ISSUE THREAD

**Issue by aitrean** [MyEtherWallet/MyEtherWallet#782]
Any action in Account/Send interface under a MetaMask-accessed account throw errors.

Error Message:
"Uncaught Error: The MetaMask Web3 object does not support synchronous methods like eth_mining without a callback parameter. See https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#dizzy-all-async---think-of-metamask-as-a-light-client"

**Comment by dternyak** [comment]
Can you provide reproductions steps / a gif of the interaction that is causing errors to be thrown?

I've just tested metamask and am not encountering any issues.

**Comment by aitrean** [comment]
Hmm, I should have checked this against the alpha build server. It seems it's a build issue on my end. I'll look more into it later.

**Comment by wbobeirne** [comment]
I've had this happen intermittently too. Will try to find steps to repro, but until then, reopening.

**Comment by wbobeirne** [comment]
This is a byproduct of opening up Redux DevTools while metamask is in redux. This is a bug with that chrome extension, and I don't think there's any way we can mitigate it.

I've been meaning to dig in and PR agains that for them, and just show ClassName(...) or something for class instances instead of trying to JSONify it.
