### ISSUE TITLE
Handle Javascript Disabled

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#79]
Right now the site just renders its broken state without Javascript. We should show a message about enabling it.

Likewise, we'll probably want to make a page that tells people to upgrade. We should settle on what features a browser NEEDS to run MEW.

**Comment by wbobeirne** [comment]
Should be straightforward with a `<noscript>` tag.

As for required features, I think the only hard requirement is local storage (Which damn near every browser has,) and a soft requirement of flexbox (A lot of messed up layouts otherwise.) But regardless, we should probably have a bottom line somewhere, if only to improve user experience / awareness of superior browsers and the potential security implications.

**Comment by dternyak** [comment]
@wbobeirne I think this issue ties in with https://github.com/MyEtherWallet/MyEtherWallet/issues/210, in that we need a way to provide messaging to users who are on platforms we do not support.

**Comment by wbobeirne** [comment]
Great, I'll add that to the bad browser check. I have a branch ready to go, just waiting to do some checking once we get browserstack sorted.
